'use strict';
let state,tab='overview';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const brl=n=>(n/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const labels={TRIAL:'Em teste',ACTIVE:'Assinatura ativa',CANCELLED:'Cancelada',PAID:'Pago',VOID:'Registro estornado'};
const input=(name,label,value='',type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const status=(value='TRIAL')=>`<label>Assinatura<select name="status">${Object.entries(labels).filter(([k])=>['TRIAL','ACTIVE','CANCELLED'].includes(k)).map(([k,v])=>`<option value="${k}" ${value===k?'selected':''}>${v}</option>`).join('')}</select></label>`;
function cents(value){if(!/^\d+(\.\d{1,2})?$/.test(value))throw Error('Informe um valor com até duas casas decimais.');const [a,b='']=value.split('.');return Number(a)*100+Number(b.padEnd(2,'0'))}
async function api(path,data){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Requested-With':'ProspectLocal'},body:JSON.stringify(data)});const result=await r.json();if(r.status===401)location.replace('/login');if(!r.ok)throw Error(result.error);return result.result}
async function refresh(){const r=await fetch('/api/admin/state');if(r.status===401){location.replace('/login');return}if(!r.ok)throw Error('Não foi possível carregar o painel.');state=await r.json();render()}
function metrics(items){return `<div class="metrics">${items.map(([label,value,foot])=>`<div class="card metric"><div class="metric-top">${label}</div><strong class="metric-number">${value}</strong><div class="metric-foot">${foot}</div></div>`).join('')}</div>`}
function render(){const m=state.metrics;$('#title').textContent={overview:'Visão geral',agencies:'Agências e acessos',payments:'Pagamentos',history:'Histórico administrativo'}[tab];document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));let html='';
if(tab==='overview')html=metrics([['Agências cadastradas',m.agencies,'Todos os cadastros'],['Assinaturas vigentes',m.active_subscriptions,'Ativas e com acesso habilitado'],['Agências que pagaram',m.paying_agencies,'Ao menos um pagamento válido'],['Acessaram em 30 dias',m.used_30_days,'Último login registrado']])+metrics([['Recebido neste mês',brl(m.month_received_cents),'Pagamentos confirmados manualmente'],['Total recebido',brl(m.received_cents),'Desconsidera registros estornados'],['Mensalidade contratada',brl(m.contracted_monthly_cents),'Valor dos planos vigentes; não é dinheiro recebido']])+`<div class="card"><h3>Sua operação comercial</h3><p>Cadastre a agência, defina o plano e a vigência e entregue o login. Pagamentos e assinaturas são registros separados: confirmar um pagamento não renova a assinatura automaticamente.</p><p>O acesso depende de conta habilitada e assinatura ativa ou em teste dentro da vigência. Suspender uma agência encerra suas sessões.</p><button data-tab="agencies" class="primary">Cadastrar primeira agência</button></div>`;
if(tab==='agencies')html=`<form id="create" class="card"><h3>Nova agência</h3><div class="form-grid">${input('name','Nome da agência','','text','required maxlength="80"')}${input('contact','Contato comercial')}${input('email','E-mail de login','','email','required autocomplete="off"')}${input('password','Senha inicial (mínimo 12 caracteres)','','password','required minlength="12" autocomplete="new-password"')}${input('plan','Plano','ProspectSTX Inicial','text','required')}${input('price','Mensalidade (R$)','197.00','number','required min="0" step="0.01"')}${status()}${input('valid_until','Acesso válido até','','date','required')}</div><p class="caption">A senha não fica visível após salvar. Compartilhe as credenciais com o cliente por um canal apropriado.</p><button class="primary">Cadastrar agência e login</button></form>${state.agencies.map(a=>`<div class="card"><div class="section-head"><div><h3>${esc(a.name)}</h3><p>${esc(a.email)} · ${esc(a.contact)}</p></div><span class="pill ${a.access_allowed?'green':'red'}">${a.access_allowed?'Acesso liberado':'Acesso bloqueado'}</span></div><p>Último acesso: ${a.last_login?esc(new Date(a.last_login).toLocaleString('pt-BR')):'Nunca acessou'}</p><form data-subscription="${a.id}"><div class="form-grid">${input('plan','Plano',a.plan,'text','required')}${input('price','Mensalidade (R$)',(a.price_cents/100).toFixed(2),'number','required min="0" step="0.01"')}${status(a.status)}${input('valid_until','Vigência',a.valid_until,'date','required')}</div><div class="actions"><button class="primary">Salvar assinatura</button><button type="button" data-access="${a.id}" data-enabled="${a.enabled?'false':'true'}">${a.enabled?'Suspender acesso':'Reativar conta'}</button></div></form><details><summary>Redefinir senha</summary><form data-password="${a.id}">${input('password','Nova senha','','password','required minlength="12" autocomplete="new-password"')}<button>Redefinir e encerrar sessões</button></form></details></div>`).join('')}`;
if(tab==='payments')html=`<form id="payment" class="card"><h3>Registrar pagamento recebido</h3><div class="form-grid"><label>Agência<select name="agency_id" required><option value="">Selecione</option>${state.agencies.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('')}</select></label>${input('amount','Valor recebido (R$)','','number','required min="0.01" step="0.01"')}${input('paid_on','Data do recebimento',state.today,'date',`required max="${state.today}"`)}${input('reference','Referência do comprovante','','text','required')}</div><p class="caption">Este registro não realiza cobrança e não renova a vigência. Para liberar ou renovar acesso, atualize a assinatura em Agências.</p><button class="primary" ${state.agencies.length?'':'disabled'}>Confirmar pagamento recebido</button></form><div class="card"><h3>Histórico de pagamentos</h3><div class="table-wrap"><table><thead><tr><th>AGÊNCIA</th><th>VALOR</th><th>DATA</th><th>REFERÊNCIA</th><th>SITUAÇÃO</th><th></th></tr></thead><tbody>${state.payments.map(p=>`<tr><td>${esc(p.agency_name)}</td><td>${brl(p.amount_cents)}</td><td>${esc(p.paid_on.split('-').reverse().join('/'))}</td><td>${esc(p.reference)}</td><td>${labels[p.status]}</td><td>${p.status==='PAID'?`<details><summary>Estornar registro</summary><form data-void-payment="${p.id}"><p>Confirmar estorno de ${brl(p.amount_cents)} para ${esc(p.agency_name)}?</p><label>Motivo do estorno<textarea name="reason" required maxlength="500" placeholder="Descreva o motivo"></textarea></label><p class="caption">Corrige o registro e os totais. Não devolve dinheiro ao cliente.</p><div class="actions"><button type="submit" class="danger">Confirmar estorno</button><button type="button" data-cancel-void>Cancelar</button></div></form></details>`:''}</td></tr>`).join('')}</tbody></table></div><p class="caption">Estornar o registro corrige o painel. Não devolve dinheiro ao cliente.</p></div>`;
if(tab==='history')html=`<div class="card"><h3>Últimas 100 alterações</h3>${state.logs.map(l=>`<div class="timeline-event"><strong>${esc({LOGIN:'Login realizado',AGENCY_CREATED:'Agência cadastrada',SUBSCRIPTION_UPDATED:'Assinatura atualizada',PAYMENT_RECORDED:'Pagamento registrado',PAYMENT_VOIDED:'Registro de pagamento estornado',ACCESS_ENABLED:'Conta reativada',ACCESS_SUSPENDED:'Acesso suspenso',PASSWORD_RESET:'Senha redefinida',ADMIN_CREATED:'Administrador criado'}[l.action]||l.action)}</strong><small>${esc(new Date(l.created_at).toLocaleString('pt-BR'))} · agência ${l.agency_id??'—'} · usuário ${l.actor??'—'}</small><p>${esc(l.detail)}</p></div>`).join('')}</div>`;
$('#content').innerHTML=html;
document.querySelectorAll('form').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const b=f.querySelector('button');b.disabled=true;try{const d=Object.fromEntries(new FormData(f));if(f.id==='create'){d.price_cents=cents(d.price);await api('/api/admin/agencies',d)}else if(f.id==='payment'){d.agency_id=Number(d.agency_id);d.amount_cents=cents(d.amount);await api('/api/admin/payments',d)}else if(f.dataset.subscription){d.agency_id=Number(f.dataset.subscription);d.price_cents=cents(d.price);await api('/api/admin/subscription',d)}else if(f.dataset.password){d.agency_id=Number(f.dataset.password);await api('/api/admin/password',d)}else if(f.dataset.voidPayment){const reason=d.reason.trim();if(!reason)throw Error('Informe o motivo do estorno.');await api('/api/admin/payments/void',{payment_id:Number(f.dataset.voidPayment),reason})}await refresh();$('#notice').textContent='Alteração salva.'}catch(err){$('#notice').textContent=err.message}finally{b.disabled=false}})
}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.tab){tab=b.dataset.tab;render()}else if(b.dataset.access){if(!confirm('Alterar o acesso desta agência? As sessões atuais serão encerradas.'))return;b.disabled=true;await api('/api/admin/access',{agency_id:Number(b.dataset.access),enabled:b.dataset.enabled==='true'});await refresh()}else if(b.hasAttribute('data-cancel-void')){const details=b.closest('details');details.querySelector('form').reset();details.open=false}}catch(err){$('#notice').textContent=err.message;b.disabled=false}});
$('#refresh').onclick=()=>refresh().catch(e=>$('#notice').textContent=e.message);
$('#logout').onclick=async()=>{await api('/api/auth/logout',{});location.replace('/login')};
refresh().catch(e=>$('#notice').textContent=e.message);
