"""Persistência PostgreSQL em schemas privados; mantém a API de acesso do motor."""
import os
import re
from contextlib import contextmanager

ID_TABLES = {'agencies','users','payments','audit','leads','messages','interactions',
             'followups','audit_logs','inbox_events','campaigns','campaign_items',
             'deliveries','automatic_jobs','prospect_candidates','prospect_search_runs',
             'search_requests','auth_attempts'}


class Row(dict):
    def __getitem__(self,key):
        return list(self.values())[key] if isinstance(key,int) else super().__getitem__(key)


def translate(sql, params=()):
    sql=sql.strip().rstrip(';')
    if sql.upper().startswith('PRAGMA '):
        return None,False
    sql=re.sub(r'\bid INTEGER PRIMARY KEY\b','id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',sql,flags=re.I)
    ignore=bool(re.match(r'INSERT OR IGNORE\b',sql,re.I))
    sql=re.sub(r'^INSERT OR IGNORE\b','INSERT',sql,flags=re.I)
    if ignore:sql+=' ON CONFLICT DO NOTHING'
    match=re.match(r'INSERT INTO\s+(\w+)\b',sql,re.I)
    returning=bool(match and match[1] in ID_TABLES and not re.search(r'\bRETURNING\b',sql,re.I))
    if returning:sql+=' RETURNING id'
    if params:
        # Alterar marcadores apenas fora dos literais SQL. Valores nunca são interpolados.
        parts=re.split("('(?:''|[^'])*')",sql)
        sql=''.join(part.replace('%','%%').replace('?','%s') if i%2==0 else part.replace('%','%%') for i,part in enumerate(parts))
    return sql,returning


class Cursor:
    def __init__(self,cursor,returning=False):
        self.cursor=cursor;self.rowcount=cursor.rowcount;self.lastrowid=None
        if returning:
            row=cursor.fetchone();self.lastrowid=row['id'] if row else None
    def fetchone(self):
        row=self.cursor.fetchone();return Row(row) if row is not None else None
    def fetchall(self):return [Row(row) for row in self.cursor.fetchall()]
    def __iter__(self):
        for row in self.cursor:yield Row(row)


class Database:
    def __init__(self,connection):self.connection=connection
    def execute(self,sql,params=()):
        query,returning=translate(sql,params)
        if query is None:return None
        return Cursor(self.connection.execute(query,params if params else None),returning)
    def executemany(self,sql,rows):
        for row in rows:self.execute(sql,row)
    def executescript(self,script):
        for sql in script.split(';'):
            if sql.strip():self.execute(sql)


@contextmanager
def postgres_db(schema):
    if not re.fullmatch(r'prospectstx_(control|agency_[1-9][0-9]*)',schema):
        raise ValueError('Schema inválido.')
    import psycopg
    from psycopg import sql
    from psycopg.rows import dict_row
    url=os.environ['DATABASE_URL']
    # Conexão cifrada e transações com search_path local, seguro para session pooler.
    with psycopg.connect(url,sslmode='require',connect_timeout=15,row_factory=dict_row,prepare_threshold=None) as connection:
        connection.execute('SELECT pg_advisory_xact_lock(hashtext(%s))',(schema,))
        connection.execute(sql.SQL('CREATE SCHEMA IF NOT EXISTS {}').format(sql.Identifier(schema)))
        connection.execute(sql.SQL('REVOKE ALL ON SCHEMA {} FROM PUBLIC').format(sql.Identifier(schema)))
        for role in ('anon','authenticated'):
            if connection.execute('SELECT 1 FROM pg_roles WHERE rolname=%s',(role,)).fetchone():
                connection.execute(sql.SQL('REVOKE ALL ON SCHEMA {} FROM {}').format(sql.Identifier(schema),sql.Identifier(role)))
        connection.execute(sql.SQL('SET LOCAL search_path TO {}, pg_catalog').format(sql.Identifier(schema)))
        yield Database(connection)
