import io
import json
import os
from pathlib import Path
import unittest
import uuid
from unittest.mock import patch

from cloud_db import translate, Row
from server import Control, COOKIE
from wsgi import build_application


class CloudTests(unittest.TestCase):
    def test_sql_and_rows(self):
        sql,ret=translate('INSERT INTO leads(company) VALUES (?)',('Example',))
        self.assertEqual(sql,'INSERT INTO leads(company) VALUES (%s) RETURNING id');self.assertTrue(ret)
        sql,ret=translate('INSERT OR IGNORE INTO schema_migrations VALUES (?)',('001',))
        self.assertEqual(sql,'INSERT INTO schema_migrations VALUES (%s) ON CONFLICT DO NOTHING');self.assertFalse(ret)
        sql,_=translate("SELECT * FROM interactions WHERE note LIKE 'REPLIED:%' AND lead_id=?",(3,))
        self.assertIn("'REPLIED:%%'",sql);self.assertIn('lead_id=%s',sql)
        sql,_=translate('CREATE TABLE t (id INTEGER PRIMARY KEY, lead_id INTEGER)')
        self.assertIn('GENERATED BY DEFAULT AS IDENTITY',sql)
        sql,_=translate('CREATE TABLE t (lead_id INTEGER PRIMARY KEY)')
        self.assertNotIn('IDENTITY',sql)
        row=Row({'id':3,'name':'Example'});self.assertEqual(row[0],3);self.assertEqual(row['name'],'Example')

    def test_wsgi_login_headers_and_admin(self):
        scratch=Path(__file__).resolve().parents[2]/'work'/('cloud-test-'+uuid.uuid4().hex)
        c=Control(scratch);c.bootstrap('admin@example.com','AdminPass12345')
        app=build_application(c,'')
        def call(path,body=None,cookie=''):
            raw=json.dumps(body).encode() if body is not None else b''
            env={'REQUEST_METHOD':'POST' if body is not None else 'GET','PATH_INFO':path,
                 'SERVER_PORT':'8766','HTTP_HOST':'127.0.0.1:8766','REMOTE_ADDR':'127.0.0.1',
                 'wsgi.input':io.BytesIO(raw),'CONTENT_LENGTH':str(len(raw)),
                 'HTTP_X_REQUESTED_WITH':'ProspectLocal','HTTP_COOKIE':cookie}
            result=[]
            data=b''.join(app(env,lambda status,headers:result.append((status,dict(headers)))))
            return result[0][0],result[0][1],data
        status,headers,_=call('/api/auth/login',{'user':'admin@example.com','password':'AdminPass12345'})
        self.assertTrue(status.startswith('200'));self.assertIn('HttpOnly',headers['Set-Cookie'])
        cookie=headers['Set-Cookie'].split(';')[0]
        status,headers,data=call('/api/admin/state',cookie=cookie)
        self.assertTrue(status.startswith('200'));self.assertEqual(json.loads(data)['metrics']['agencies'],0)
        status,headers,_=call('/',cookie=cookie);self.assertEqual(headers['Location'],'/admin')
        status,_,_=call('/api/admin/state');self.assertTrue(status.startswith('401'))

    def test_public_backend_host_and_origin(self):
        scratch=Path(__file__).resolve().parents[2]/'work'/('cloud-test-'+uuid.uuid4().hex)
        with patch.dict(os.environ,{'ORBIT_V2_BACKEND_URL':'https://example.onrender.com'}):
            app=build_application(Control(scratch),'https://prospecstxx.netlify.app')
            result=[]
            env={'REQUEST_METHOD':'GET','PATH_INFO':'/healthz','SERVER_PORT':'443',
                 'HTTP_HOST':'example.onrender.com','wsgi.input':io.BytesIO(b'')}
            data=b''.join(app(env,lambda status,headers:result.append(status)))
            self.assertTrue(result[0].startswith('200'));self.assertTrue(json.loads(data)['ok'])


if __name__=='__main__':unittest.main()
