CREATE TABLE IF NOT EXISTS leads (
 id INTEGER PRIMARY KEY, company TEXT NOT NULL, data TEXT NOT NULL,
 status TEXT NOT NULL DEFAULT 'NEW', score INTEGER NOT NULL DEFAULT 0,
 analysis TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
 do_not_contact INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS identities (
 kind TEXT NOT NULL, value TEXT NOT NULL, lead_id INTEGER NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
 PRIMARY KEY(kind,value)
);
CREATE TABLE IF NOT EXISTS messages (
 id INTEGER PRIMARY KEY, lead_id INTEGER NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
 variant TEXT NOT NULL, body TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'PENDING',
 created_at TEXT NOT NULL, approved_at TEXT
);
CREATE TABLE IF NOT EXISTS interactions (
 id INTEGER PRIMARY KEY, lead_id INTEGER NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
 message_id INTEGER REFERENCES messages(id) ON DELETE SET NULL, kind TEXT NOT NULL,
 note TEXT NOT NULL, created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS followups (
 id INTEGER PRIMARY KEY, lead_id INTEGER NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
 due_at TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'PENDING', message_id INTEGER REFERENCES messages(id) ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS audit_logs (
 id INTEGER PRIMARY KEY, lead_id INTEGER REFERENCES leads(id) ON DELETE CASCADE,
 action TEXT NOT NULL, detail TEXT NOT NULL, created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS schema_migrations (version TEXT PRIMARY KEY);
